name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  gap: ^3.0.1
  connectivity_plus: ^6.0.5
  logger: ^2.4.0

  # Icons
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6

  # Product Specific
  http: ^1.2.2
  geocoding: ^3.0.0
  lottie: ^3.1.3
  geolocator: ^13.0.1


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/fonts/
    - assets/animations/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic